app_name = "erpnext_pdf_renaming"
app_title = "ERPNext PDF Renaming"
app_publisher = "Joeryan De Chavez"
app_description = "Temporary-processing invoice PDF renaming page for ERPNext"
app_email = ""
app_license = "MIT"
